import jsPDF from 'jspdf'
import { DECORATION_ELEMENTS } from './photoBookTemplates'

export async function generatePhotoBookPDF(options) {
  const { title, pages, template, getMediaPath } = options

  if (!pages || !pages.length || !template) {
    throw new Error('缺少必要参数')
  }

  const doc = new jsPDF({
    orientation: template.height > template.width ? 'portrait' : 'landscape',
    unit: 'mm',
    format: [template.width, template.height],
    putOnlyUsedFonts: true
  })

  doc.setProperties({
    title: title || 'Photo Book',
    subject: 'Generated by TravelMemory',
    creator: 'TravelMemory App'
  })

  for (let pageIdx = 0; pageIdx < pages.length; pageIdx++) {
    const page = pages[pageIdx]

    if (pageIdx > 0) {
      doc.addPage([template.width, template.height], template.height > template.width ? 'portrait' : 'landscape')
    }

    if (page.background_color && page.background_color !== '#ffffff') {
      doc.setFillColor(page.background_color)
      doc.rect(0, 0, template.width, template.height, 'F')
    }

    const elements = page.elements || []
    const sortedElements = [...elements].sort((a, b) => (a.z_index || 0) - (b.z_index || 0))

    for (const el of sortedElements) {
      try {
        await renderElement(doc, el, template, getMediaPath)
      } catch (e) {
        console.warn('渲染元素失败:', e)
      }
    }
  }

  return doc.output('arraybuffer')
}

async function renderElement(doc, el, template, getMediaPath) {
  const type = el.element_type

  switch (type) {
    case 'photo':
    case 'polaroid_photo':
      await renderPhoto(doc, el, getMediaPath, type === 'polaroid_photo')
      break
    case 'text':
      renderText(doc, el)
      break
    case 'decoration':
      renderDecoration(doc, el)
      break
    default:
      break
  }
}

async function renderPhoto(doc, el, getMediaPath, isPolaroid) {
  const mediaPath = getMediaPath ? getMediaPath(el.media_id) : null

  if (!mediaPath) {
    doc.setFillColor('#f5f0e6')
    doc.rect(el.x, el.y, el.width, el.height, 'F')
    doc.setTextColor('#b0a08a')
    doc.setFontSize(8)
    doc.text('照片', el.x + el.width / 2, el.y + el.height / 2, { align: 'center', baseline: 'middle' })
    return
  }

  try {
    const imgData = await loadImageAsBase64(mediaPath)

    if (!imgData) {
      throw new Error('图片加载失败')
    }

    if (isPolaroid) {
      const padX = el.width * 0.08
      const padY = el.height * 0.08
      const bottomPad = el.height * 0.22

      doc.setFillColor('#ffffff')
      doc.rect(el.x, el.y, el.width, el.height, 'F')

      const imgX = el.x + padX
      const imgY = el.y + padY
      const imgW = el.width - padX * 2
      const imgH = el.height - padY - bottomPad

      doc.addImage(imgData, 'JPEG', imgX, imgY, imgW, imgH, undefined, 'FAST')

      doc.setDrawColor('#e0d8cc')
      doc.setLineWidth(0.1)
      doc.rect(el.x, el.y, el.width, el.height, 'S')
    } else {
      doc.addImage(imgData, 'JPEG', el.x, el.y, el.width, el.height, undefined, 'FAST')
    }
  } catch (e) {
    console.error('添加图片失败:', e)
    doc.setFillColor('#f5f0e6')
    doc.rect(el.x, el.y, el.width, el.height, 'F')
  }
}

function renderText(doc, el) {
  const style = el.style || {}
  const content = el.content || ''

  if (!content) return

  const fontSize = style.fontSize || 14
  const fontWeight = style.fontWeight || 'normal'
  const color = style.color || '#333333'
  const textAlign = style.textAlign || 'left'
  const fontStyle = style.fontStyle || 'normal'

  let fontType = 'normal'
  if (fontWeight === 'bold' && fontStyle === 'italic') {
    fontType = 'bolditalic'
  } else if (fontWeight === 'bold') {
    fontType = 'bold'
  } else if (fontStyle === 'italic') {
    fontType = 'italic'
  }

  try {
    doc.setFont('helvetica', fontType)
  } catch (e) {
    doc.setFont(doc.getFont().fontName, fontType)
  }

  doc.setFontSize(fontSize)
  doc.setTextColor(color)

  const lineHeight = (style.lineHeight || 1.4) * fontSize * 0.352778

  const textX = textAlign === 'center'
    ? el.x + el.width / 2
    : textAlign === 'right'
      ? el.x + el.width
      : el.x

  const textY = el.y + lineHeight * 0.8

  const lines = doc.splitTextToSize(content, el.width - 2)

  if (Array.isArray(lines)) {
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i]
      const y = textY + i * lineHeight
      if (y > el.y + el.height - lineHeight) break

      doc.text(line, textX, y, {
        align: textAlign,
        baseline: 'top'
      })
    }
  }
}

function renderDecoration(doc, el) {
  const content = el.content || ''
  const decoration = DECORATION_ELEMENTS.find(d => d.id === content || d.emoji === content)

  if (!decoration) return

  const centerX = el.x + el.width / 2
  const centerY = el.y + el.height / 2

  doc.setFontSize(Math.min(el.width, el.height) * 2)
  doc.setTextColor('#333333')

  try {
    doc.text(decoration.emoji || '✨', centerX, centerY, {
      align: 'center',
      baseline: 'middle'
    })
  } catch (e) {
    doc.setFillColor('#f5f0e6')
    doc.rect(el.x, el.y, el.width, el.height, 'F')
  }
}

function loadImageAsBase64(filePath) {
  return new Promise((resolve, reject) => {
    const img = new Image()
    img.onload = () => {
      try {
        const canvas = document.createElement('canvas')
        canvas.width = img.width
        canvas.height = img.height
        const ctx = canvas.getContext('2d')
        ctx.drawImage(img, 0, 0)
        const dataUrl = canvas.toDataURL('image/jpeg', 0.92)
        resolve(dataUrl)
      } catch (e) {
        reject(e)
      }
    }
    img.onerror = (e) => {
      reject(e)
    }
    img.src = 'file:///' + filePath.replace(/\\/g, '/')
  })
}
